# Generated by Django 2.2.2 on 2019-12-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='over',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Average'),
        ),
    ]
