# Generated by Django 2.2.2 on 2019-12-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20191209_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='course',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistic',
            name='university',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statistic',
            name='f21',
            field=models.IntegerField(verbose_name='Miscellenaous Factor 1'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='f22',
            field=models.IntegerField(verbose_name='Miscellenaous Factor 2'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='f23',
            field=models.IntegerField(verbose_name='Miscellenaous Factor 3'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='f24',
            field=models.IntegerField(verbose_name='Miscellenaous Factor 4'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='f25',
            field=models.IntegerField(verbose_name='Miscellenaous Factor 5'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
